INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16639, 'VMCG installer_de_DE.xlz', '1', 900, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16640, 'VMCG installer_ja_JP.xlz', '1', 900, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16641, 'VMCG installer_fr_FR.xlz', '1', 900, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16642, 'VMCG installer_es_ES.xlz', '1', 900, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16643, 'VMCG installer_ko_KR.xlz', '1', 900, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16644, 'VMCG installer_zh_CN.xlz', '1', 900, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16645, 'VMCG installer_zh_TW.xlz', '1', 900, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16788, 'AW People Search 1.1.1 iOS+Android-WN_ko_KR.xlz', '1', 907, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16789, 'AW People Search 1.1.1 iOS+Android-WN_nl_NL.xlz', '1', 907, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16794, 'AW People Search 1.1.1 Android only-WN_cs_CZ.xlz', '1', 908, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16795, 'AW People Search 1.1.1 Android only-WN_pl_PL.xlz', '1', 908, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16796, 'AW People Search 1.1.1 Android only-WN_tr_TR.xlz', '1', 908, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16797, 'AW People Search 1.1.1 Android only-WN_zh_TW.xlz', '1', 908, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16798, 'AW People Search 1.1.1 Android only-WN_da_DK.xlz', '1', 908, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16990, 'AW Tunnel 4.0.0 for Android-WN_cs_CZ.xlz', '1', 922, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16991, 'AW Tunnel 4.0.0 for Android-WN_it_IT.xlz', '1', 922, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16992, 'AW Tunnel 4.0.0 for Android-WN_fr_FR.xlz', '1', 922, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16993, 'AW Tunnel 4.0.0 for Android-WN_de_DE.xlz', '1', 922, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16994, 'AW Tunnel 4.0.0 for Android-WN_da_DK.xlz', '1', 922, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16995, 'AW Tunnel 4.0.0 for Android-WN_es_ES.xlz', '1', 922, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16997, 'AW Tunnel 4.0.0 for Android-WN_ko_KR.xlz', '1', 922, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (16999, 'AW Tunnel 4.0.0 for Android-WN_zh_CN.xlz', '1', 922, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17001, 'AW Tunnel 4.0.0 for Android-WN_pt_BR.xlz', '1', 922, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17002, 'AW Tunnel 4.0.0 for Android-WN_ru_RU.xlz', '1', 922, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17003, 'AW Tunnel 4.0.0 for Android-WN_nl_NL.xlz', '1', 922, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17004, 'AW Tunnel 4.0.0 for Android-WN_tr_TR.xlz', '1', 922, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17005, 'AW Tunnel 4.0.0 for Android-WN_zh_TW.xlz', '1', 922, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17033, 'AW Boxer 4.13 for Android-WN_es_ES.xlz', '1', 926, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17034, 'AW Boxer 4.13 for Android-WN_cs_CZ.xlz', '1', 926, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17035, 'AW Boxer 4.13 for Android-WN_de_DE.xlz', '1', 926, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17037, 'AW Boxer 4.13 for Android-WN_ko_KR.xlz', '1', 926, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17038, 'AW Boxer 4.13 for Android-WN_nl_NL.xlz', '1', 926, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17040, 'AW Boxer 4.13 for Android-WN_ru_RU.xlz', '1', 926, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17041, 'AW Boxer 4.13 for Android-WN_fr_FR.xlz', '1', 926, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17042, 'AW Boxer 4.13 for Android-WN_ja_JP.xlz', '1', 926, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17043, 'AW Boxer 4.13 for Android-WN_pt_BR.xlz', '1', 926, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17044, 'AW Boxer 4.13 for Android-WN_it_IT.xlz', '1', 926, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17045, 'AW Boxer 4.13 for Android-WN_tr_TR.xlz', '1', 926, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17046, 'AW Boxer 4.13 for Android-WN_zh_CN.xlz', '1', 926, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17048, 'AW Boxer 4.13 for Android-WN_zh_TW.xlz', '1', 926, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17049, 'AW Boxer 4.13 for iOS-WN_de_DE.xlz', '1', 927, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17050, 'AW Boxer 4.13 for iOS-WN_es_ES.xlz', '1', 927, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17051, 'AW Boxer 4.13 for iOS-WN_ja_JP.xlz', '1', 927, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17052, 'AW Boxer 4.13 for iOS-WN_ko_KR.xlz', '1', 927, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17053, 'AW Boxer 4.13 for iOS-WN_fr_FR.xlz', '1', 927, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17054, 'AW Boxer 4.13 for iOS-WN_it_IT.xlz', '1', 927, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17055, 'AW Boxer 4.13 for iOS-WN_pt_BR.xlz', '1', 927, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17056, 'AW Boxer 4.13 for iOS-WN_nl_NL.xlz', '1', 927, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17058, 'AW Boxer 4.13 for iOS-WN_zh_CN.xlz', '1', 927, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17059, 'AW Boxer 4.13 for iOS-WN_ru_RU.xlz', '1', 927, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17158, 'AW Browser 6.13 for Android+iOS_de_DE.xlz', '1', 935, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17159, 'AW Browser 6.13 for Android+iOS_es_ES.xlz', '1', 935, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17160, 'AW Browser 6.13 for Android+iOS_it_IT.xlz', '1', 935, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17161, 'AW Browser 6.13 for Android+iOS_fr_FR.xlz', '1', 935, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17163, 'AW Browser 6.13 for Android+iOS_pt_BR.xlz', '1', 935, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17164, 'AW Browser 6.13 for Android+iOS_ja_JP.xlz', '1', 935, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17165, 'AW Browser 6.13 for Android+iOS_ko_KR.xlz', '1', 935, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17166, 'AW Browser 6.13 for Android+iOS_nl_NL.xlz', '1', 935, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17167, 'AW Browser 6.13 for Android+iOS_ru_RU.xlz', '1', 935, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17168, 'AW Browser 6.13 for Android+iOS_zh_CN.xlz', '1', 935, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17170, 'AW Browser 6.13 for Android only-WN_zh_TW.xlz', '1', 936, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17171, 'AW Browser 6.13 for Android only-WN_cs_CZ.xlz', '1', 936, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17172, 'AW Browser 6.13 for Android only-WN_da_DK.xlz', '1', 936, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17173, 'AW Browser 6.13 for Android only-WN_tr_TR.xlz', '1', 936, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17735, 'DRaaS_M4_RN_20180516_de_DE.xlz', '1', 963, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17738, 'DRaaS_M4_RN_20180516_es_ES.xlz', '1', 963, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17742, 'DRaaS_M4_RN_20180516_fr_FR.xlz', '1', 963, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17749, 'DRaaS_M4_RN_20180516_ja_JP.xlz', '1', 963, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17751, 'DRaaS_M4_RN_20180516_ko_KR.xlz', '1', 963, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (17752, 'DRaaS_M4_RN_20180516_zh_CN.xlz', '1', 963, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18043, 'DRaaS_M4_RN_20180518_fr_FR.xlz', '1', 976, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18044, 'DRaaS_M4_RN_20180518_de_DE.xlz', '1', 976, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18045, 'DRaaS_M4_RN_20180518_es_ES.xlz', '1', 976, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18046, 'DRaaS_M4_RN_20180518_ja_JP.xlz', '1', 976, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18047, 'DRaaS_M4_RN_20180518_zh_CN.xlz', '1', 976, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18048, 'DRaaS_M4_RN_20180518_ko_KR.xlz', '1', 976, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18050, 'vCD9101_UI_Drop1_de_DE.xlz', '1', 977, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18052, 'vCD9101_UI_Drop1_fr_FR.xlz', '1', 977, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18053, 'vCD9101_UI_Drop1_it_IT.xlz', '1', 977, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18054, 'vCD9101_UI_Drop1_es_ES.xlz', '1', 977, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18055, 'vCD9101_UI_Drop1_ja_JP.xlz', '1', 977, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18056, 'vCD9101_UI_Drop1_ko_KR.xlz', '1', 977, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18057, 'tasks_vCD9101_UI_Drop1_56030_zh_CN_xliff.xlz', '1', 977, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18333, 'SRM_81_DRaaS_M4_RN_refresh_20180521_es_ES.xlz', '1', 990, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18334, 'SRM_81_DRaaS_M4_RN_refresh_20180521_fr_FR.xlz', '1', 990, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18335, 'SRM_81_DRaaS_M4_RN_refresh_20180521_ja_JP.xlz', '1', 990, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18336, 'SRM_81_DRaaS_M4_RN_refresh_20180521_ko_KR.xlz', '1', 990, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18337, 'SRM_81_DRaaS_M4_RN_refresh_20180521_zh_TW.xlz', '1', 990, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18338, 'SRM_81_DRaaS_M4_RN_refresh_20180521_zh_CN.xlz', '1', 990, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18340, 'VR_81_RN_refresh_20180521_es_ES.xlz', '1', 990, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18341, 'VR_81_RN_refresh_20180521_fr_FR.xlz', '1', 990, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18342, 'VR_81_RN_refresh_20180521_ja_JP.xlz', '1', 990, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18343, 'VR_81_RN_refresh_20180521_ko_KR.xlz', '1', 990, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18344, 'VR_81_RN_refresh_20180521_zh_CN.xlz', '1', 990, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18345, 'VR_81_RN_refresh_20180521_zh_TW.xlz', '1', 990, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18374, 'vmcui-m5-drop-20180522_es_ES.xlz', '1', 998, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18375, 'vmcui-m5-drop-20180522_zh_CN.xlz', '1', 998, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18376, 'vmcui-m5-drop-20180522_de_DE.xlz', '1', 998, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18377, 'vmcui-m5-drop-20180522_ja_JP.xlz', '1', 998, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18378, 'vmcui-m5-drop-20180522_zh_TW.xlz', '1', 998, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18379, 'vmcui-m5-drop-20180522_fr_FR.xlz', '1', 998, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18380, 'vmcui-m5-drop-20180522_ko_KR.xlz', '1', 998, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18382, 'vRA75_UI_Drop 1_zh_CN.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18384, 'vRA75_UI_Drop 1_nl_NL.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18385, 'vRA75_UI_Drop 1_ko_KR.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18387, 'vRA75_UI_Drop1_Container_zh_CN.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18389, 'vRA75_UI_Drop1_Container_pt_BR.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18390, 'vRA75_UI_Drop1_Container_nl_NL.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18391, 'vRA75_UI_Drop1_Container_ko_KR.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18392, 'vRA75_UI_Drop1_Container_ja_JP.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18393, 'vRA75_UI_Drop1_Container_it_IT.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18394, 'vRA75_UI_Drop1_Container_es_ES.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18395, 'vRA75_UI_Drop1_Container_de_DE.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18396, 'vRA75_UI_Drop1_Container_fr_FR.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18398, 'vRA75_UI_Drop1_Forms_nl_NL.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18400, 'vRA75_UI_Drop1_Forms_zh_CN.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18401, 'vRA75_UI_Drop1_Forms_pt_BR.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18402, 'vRA75_UI_Drop1_Forms_de_DE.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18403, 'vRA75_UI_Drop1_Forms_it_IT.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18404, 'vRA75_UI_Drop1_Forms_fr_FR.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18405, 'vRA75_UI_Drop1_Forms_ko_KR.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18406, 'vRA75_UI_Drop1_Forms_ja_JP.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18407, 'vRA75_UI_Drop1_Forms_es_ES.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18408, 'vRA75_UI_Drop 1_ja_JP.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18409, 'vRA75_UI_Drop 1_de_DE.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18410, 'vRA75_UI_Drop 1_it_IT.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18411, 'vRA75_UI_Drop 1_fr_FR.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18412, 'vRA75_UI_Drop 1_pt_BR.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18413, 'vRA75_UI_Drop 1_es_ES.xlz', '1', 999, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18509, 'VMware_Airwatch_PIVD_Description_20180524_zh_CN.xlz', '1', 1009, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18510, 'VMware_Airwatch_PIVD_Description_20180524_sv_SE.xlz', '1', 1009, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18511, 'VMware_Airwatch_PIVD_Description_20180524_nl_NL.xlz', '1', 1009, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18512, 'VMware_Airwatch_PIVD_Description_20180524_ko_KR.xlz', '1', 1009, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18513, 'VMware_Airwatch_PIVD_Description_20180524_pt_BR.xlz', '1', 1009, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18514, 'VMware_Airwatch_PIVD_Description_20180524_zh_TW.xlz', '1', 1009, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18515, 'VMware_Airwatch_PIVD_Description_20180524_ja_JP.xlz', '1', 1009, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18516, 'VMware_Airwatch_PIVD_Description_20180524_es_ES.xlz', '1', 1009, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18517, 'VMware_Airwatch_PIVD_Description_20180524_fr_FR.xlz', '1', 1009, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18518, 'VMware_Airwatch_PIVD_Description_20180524_de_DE.xlz', '1', 1009, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18519, 'VMware_Airwatch_PIVD_Description_20180524_it_IT.xlz', '1', 1009, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18541, 'vsphere_vcenter_server_6.7.0a_rn_20180524_es_ES.xlz', '1', 1010, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18542, 'vsphere_vcenter_server_6.7.0a_rn_20180524_fr_FR.xlz', '1', 1010, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18543, 'vsphere_vcenter_server_6.7.0a_rn_20180524_zh_CN.xlz', '1', 1010, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18544, 'vsphere_vcenter_server_6.7.0a_rn_20180524_zh_TW.xlz', '1', 1010, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18545, 'vsphere_vcenter_server_6.7.0a_rn_20180524_ko_KR.xlz', '1', 1010, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18546, 'vsphere_vcenter_server_6.7.0a_rn_20180524_ja_JP.xlz', '1', 1010, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18811, 'VMware_Airwatch_PIVD_Description_20180524_ru_RU.xlz', '1', 1020, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18877, 'AW Agent 8.2 for Android-WN_it_IT.xlz', '1', 1024, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18878, 'AW Agent 8.2 for Android-WN_cs_CZ.xlz', '1', 1024, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18879, 'AW Agent 8.2 for Android-WN_da_DK.xlz', '1', 1024, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18880, 'AW Agent 8.2 for Android-WN_es_ES.xlz', '1', 1024, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18881, 'AW Agent 8.2 for Android-WN_de_DE.xlz', '1', 1024, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18882, 'AW Agent 8.2 for Android-WN_fr_FR.xlz', '1', 1024, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18883, 'AW Agent 8.2 for Android-WN_pt_BR.xlz', '1', 1024, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18884, 'AW Agent 8.2 for Android-WN_ru_RU.xlz', '1', 1024, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18885, 'AW Agent 8.2 for Android-WN_ja_JP.xlz', '1', 1024, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18886, 'AW Agent 8.2 for Android-WN_ko_KR.xlz', '1', 1024, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18887, 'AW Agent 8.2 for Android-WN_nl_NL.xlz', '1', 1024, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18889, 'AW Agent 8.2 for Android-WN_sv_SE.xlz', '1', 1024, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18890, 'AW Agent 8.2 for Android-WN_tr_TR.xlz', '1', 1024, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18891, 'AW Agent 8.2 for Android-WN_zh_TW.xlz', '1', 1024, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (18892, 'AW Agent 8.2 for Android-WN_zh_CN.xlz', '1', 1024, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19591, 'VMRC_1003_UI_drop1_de_DE.xlz', '1', 1061, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19592, 'VMRC_1003_UI_drop1_es_ES.xlz', '1', 1061, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19593, 'VMRC_1003_UI_drop1_fr_FR.xlz', '1', 1061, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19594, 'VMRC_1003_UI_drop1_it_IT.xlz', '1', 1061, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19595, 'VMRC_1003_UI_drop1_ja_JP.xlz', '1', 1061, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19596, 'VMRC_1003_UI_drop1_ko_KR.xlz', '1', 1061, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19598, 'VMRC_1003_UI_drop1_pt_BR.xlz', '1', 1061, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19599, 'VMRC_1003_UI_drop1_ru_RU.xlz', '1', 1061, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19600, 'VMRC_1003_UI_drop1_zh_CN.xlz', '1', 1061, '1', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19601, 'VMRC_1003_UI_drop1_zh_TW.xlz', '1', 1061, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19786, 'AW Boxer Android 4.13.1 & iOS 4.13.2-WN_da_DK.xlz', '1', 1071, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19787, 'AW Boxer Android 4.13.1 & iOS 4.13.2-WN_cs_CZ.xlz', '1', 1071, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19788, 'AW Boxer Android 4.13.1 & iOS 4.13.2-WN_fr_FR.xlz', '1', 1071, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19789, 'AW Boxer Android 4.13.1 & iOS 4.13.2-WN_it_IT.xlz', '1', 1071, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19790, 'AW Boxer Android 4.13.1 & iOS 4.13.2-WN_pt_BR.xlz', '1', 1071, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19791, 'AW Boxer Android 4.13.1 & iOS 4.13.2-WN_nl_NL.xlz', '1', 1071, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19792, 'AW Boxer Android 4.13.1 & iOS 4.13.2-WN_de_DE.xlz', '1', 1071, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19793, 'AW Boxer Android 4.13.1 & iOS 4.13.2-WN_es_ES.xlz', '1', 1071, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19794, 'AW Boxer Android 4.13.1 & iOS 4.13.2-WN_ja_JP.xlz', '1', 1071, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19795, 'AW Boxer Android 4.13.1 & iOS 4.13.2-WN_ko_KR.xlz', '1', 1071, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19796, 'AW Boxer Android 4.13.1 & iOS 4.13.2-WN_ru_RU.xlz', '1', 1071, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19797, 'AW Boxer Android 4.13.1 & iOS 4.13.2-WN_pl_PL.xlz', '1', 1071, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19798, 'AW Boxer Android 4.13.1 & iOS 4.13.2-WN_sv_SE.xlz', '1', 1071, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19799, 'AW Boxer Android 4.13.1 & iOS 4.13.2-WN_zh_CN.xlz', '1', 1071, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19800, 'AW Boxer Android 4.13.1 & iOS 4.13.2-WN_zh_TW.xlz', '1', 1071, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19801, 'AW Boxer Android 4.13.1 & iOS 4.13.2-WN_tr_TR.xlz', '1', 1071, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19900, 'vsphere_vcenter_server_6.7.0a_drop2_rn_20180606_de_DE.xlz', '1', 1075, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19905, 'vsphere_vcenter_server_6.7.0a_drop2_rn_20180606_ko_KR.xlz', '1', 1075, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19906, 'vsphere_vcenter_server_6.7.0a_drop2_rn_20180606_fr_FR.xlz', '1', 1075, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19907, 'vsphere_vcenter_server_6.7.0a_drop2_rn_20180606_ja_JP.xlz', '1', 1075, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19908, 'vsphere_vcenter_server_6.7.0a_drop2_rn_20180606_es_ES.xlz', '1', 1075, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19909, 'vsphere_vcenter_server_6.7.0a_drop2_rn_20180606_zh_TW.xlz', '1', 1075, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (19910, 'vsphere_vcenter_server_6.7.0a_drop2_rn_20180606_zh_CN.xlz', '1', 1075, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21347, 'AW Content Locker 4.13.3 for iOS_de_DE.xlz', '0', 1092, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21348, 'AW Content Locker 4.13.3 for iOS_it_IT.xlz', '1', 1092, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21349, 'AW Content Locker 4.13.3 for iOS_fr_FR.xlz', '1', 1092, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21350, 'AW Content Locker 4.13.3 for iOS_es_ES.xlz', '1', 1092, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21351, 'AW Content Locker 4.13.3 for iOS_sv_SE.xlz', '1', 1092, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21352, 'AW Content Locker 4.13.3 for iOS_nl_NL.xlz', '0', 1092, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21353, 'AW Content Locker 4.13.3 for iOS_ru_RU.xlz', '1', 1092, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21354, 'AW Content Locker 4.13.3 for iOS_ko_KR.xlz', '0', 1092, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21355, 'AW Content Locker 4.13.3 for iOS_pt_BR.xlz', '0', 1092, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21356, 'AW Content Locker 4.13.3 for iOS_ja_JP.xlz', '1', 1092, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21357, 'AW Content Locker 4.13.3 for iOS_zh_CN.xlz', '1', 1092, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21358, 'AW Content Locker 3.13.3 for Android_cs_CZ.xlz', '0', 1093, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21359, 'AW Content Locker 3.13.3 for Android_da_DK.xlz', '0', 1093, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21360, 'AW Content Locker 3.13.3 for Android_pl_PL.xlz', '0', 1093, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21361, 'AW Content Locker 3.13.3 for Android_tr_TR.xlz', '0', 1093, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21362, 'AW Content Locker 3.13.3 for Android_zh_TW.xlz', '1', 1093, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21615, 'AW Relay Service v2.8.0 for Android_20180612_cs_CZ.xlz', '1', 1104, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21616, 'AW Relay Service v2.8.0 for Android_20180612_da_DK.xlz', '0', 1104, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21617, 'AW Relay Service v2.8.0 for Android_20180612_de_DE.xlz', '1', 1104, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21618, 'AW Relay Service v2.8.0 for Android_20180612_ja_JP.xlz', '1', 1104, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21619, 'AW Relay Service v2.8.0 for Android_20180612_ko_KR.xlz', '1', 1104, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21620, 'AW Relay Service v2.8.0 for Android_20180612_nl_NL.xlz', '1', 1104, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21621, 'AW Relay Service v2.8.0 for Android_20180612_es_ES.xlz', '1', 1104, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21622, 'AW Relay Service v2.8.0 for Android_20180612_fr_FR.xlz', '1', 1104, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21623, 'AW Relay Service v2.8.0 for Android_20180612_it_IT.xlz', '1', 1104, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21624, 'AW Relay Service v2.8.0 for Android_20180612_pl_PL.xlz', '0', 1104, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21625, 'AW Relay Service v2.8.0 for Android_20180612_pt_BR.xlz', '1', 1104, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21626, 'AW Relay Service v2.8.0 for Android_20180612_sv_SE.xlz', '1', 1104, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21627, 'AW Relay Service v2.8.0 for Android_20180612_ru_RU.xlz', '1', 1104, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21628, 'AW Relay Service v2.8.0 for Android_20180612_zh_CN.xlz', '1', 1104, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21629, 'AW Relay Service v2.8.0 for Android_20180612_zh_TW.xlz', '1', 1104, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21630, 'AW Relay Service v2.8.0 for Android_20180612_tr_TR.xlz', '1', 1104, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21852, 'vmcui-m5-drop-20180612_de_DE.xlz', '1', 1114, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21853, 'vmcui-m5-drop-20180612_fr_FR.xlz', '1', 1114, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21854, 'vmcui-m5-drop-20180612_es_ES.xlz', '1', 1114, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21855, 'vmcui-m5-drop-20180612_ja_JP.xlz', '1', 1114, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21857, 'vmcui-m5-drop-20180612_zh_CN.xlz', '1', 1114, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21859, 'tasks_vmcui-m5-drop-20180612_58921_ko_KR_xliff.xlz', '1', 1114, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21863, 'SRM_81_DRaaS_RN_refresh_20180612_ja_JP.xlz', '1', 1117, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21864, 'SRM_81_DRaaS_RN_refresh_20180612_ko_KR.xlz', '1', 1117, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21865, 'SRM_81_DRaaS_RN_refresh_20180612_zh_CN.xlz', '1', 1117, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21866, 'SRM_81_DRaaS_RN_refresh_20180612_zh_TW.xlz', '1', 1117, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21867, 'tasks_SRM_81_DRaaS_RN_refresh_20180612_58939_de_DE_xliff.xlz', '1', 1117, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (21868, 'tasks_SRM_81_DRaaS_RN_refresh_20180612_58940_es_ES_xliff.xlz', '1', 1117, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23179, 'vSphere6.7_for_vSAN_UI_drop1_de_DE.xlz', '1', 1175, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23180, 'vSphere6.7_for_vSAN_UI_drop1_es_ES.xlz', '1', 1175, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23181, 'vSphere6.7_for_vSAN_UI_drop1_ja_JP.xlz', '1', 1175, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23182, 'vSphere6.7_for_vSAN_UI_drop1_fr_FR.xlz', '1', 1175, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23183, 'vSphere6.7_for_vSAN_UI_drop1_zh_TW.xlz', '1', 1175, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23184, 'vSphere6.7_for_vSAN_UI_drop1_ko_KR.xlz', '1', 1175, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23185, 'vSphere6.7_for_vSAN_UI_drop1_zh_CN.xlz', '1', 1175, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23386, 'AW_VMware Boxer 4.14 for Android_20180621_cs_CZ.xlz', '1', 1187, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23387, 'AW_VMware Boxer 4.14 for Android_20180621_ko_KR.xlz', '1', 1187, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23388, 'AW_VMware Boxer 4.14 for Android_20180621_da_DK.xlz', '1', 1187, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23389, 'AW_VMware Boxer 4.14 for Android_20180621_it_IT.xlz', '1', 1187, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23390, 'AW_VMware Boxer 4.14 for Android_20180621_es_ES.xlz', '1', 1187, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23391, 'AW_VMware Boxer 4.14 for Android_20180621_de_DE.xlz', '1', 1187, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23392, 'AW_VMware Boxer 4.14 for Android_20180621_ja_JP.xlz', '1', 1187, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23393, 'AW_VMware Boxer 4.14 for Android_20180621_nl_NL.xlz', '1', 1187, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23395, 'AW_VMware Boxer 4.14 for Android_20180621_pt_BR.xlz', '1', 1187, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23396, 'AW_VMware Boxer 4.14 for Android_20180621_pl_PL.xlz', '1', 1187, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23397, 'AW_VMware Boxer 4.14 for Android_20180621_ru_RU.xlz', '1', 1187, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23398, 'AW_VMware Boxer 4.14 for Android_20180621_zh_CN.xlz', '1', 1187, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23399, 'AW_VMware Boxer 4.14 for Android_20180621_zh_TW.xlz', '1', 1187, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23400, 'AW_VMware Boxer 4.14 for Android_20180621_tr_TR.xlz', '1', 1187, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (23401, 'AW_VMware Boxer 4.14 for Android_20180621_sv_SE.xlz', '1', 1187, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24269, 'tasks_AW_VMware_People_Search_1.2_for_Android_20180627_60697_cs_CZ_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24270, 'tasks_AW_VMware_People_Search_1.2_for_Android_20180627_60698_da_DK_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24271, 'tasks_AW_VMware_People_Search_1.2_for_Android_20180627_60699_de_DE_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24272, 'tasks_AW_VMware_People_Search_1.2_for_Android_20180627_60700_es_ES_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24273, 'tasks_AW_VMware_People_Search_1.2_for_Android_20180627_60701_fr_FR_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24274, 'tasks_AW_VMware_People_Search_1.2_for_Android_20180627_60702_it_IT_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24275, 'tasks_AW_VMware_People_Search_1.2_for_Android_20180627_60703_ja_JP_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24276, 'tasks_AW_VMware_People_Search_1.2_for_Android_20180627_60704_ko_KR_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24277, 'tasks_AW_VMware_People_Search_1.2_for_Android_20180627_60705_nl_NL_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24278, 'tasks_AW_VMware_People_Search_1.2_for_Android_20180627_60706_pl_PL_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24279, 'tasks_AW_VMware_People_Search_1.2_for_Android_20180627_60707_pt_BR_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24280, 'tasks_AW_VMware_People_Search_1.2_for_Android_20180627_60708_ru_RU_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24281, 'tasks_AW_VMware_People_Search_1.2_for_Android_20180627_60709_sv_SE_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24282, 'tasks_AW_VMware_People_Search_1.2_for_Android_20180627_60710_tr_TR_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24283, 'tasks_AW_VMware_People_Search_1.2_for_Android_20180627_60711_zh_CN_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24284, 'tasks_AW_VMware_People_Search_1.2_for_Android_20180627_60712_zh_TW_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24285, 'tasks_AW_VMware_People_Search_1.2_for_iOS_20180627_60713_de_DE_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24286, 'tasks_AW_VMware_People_Search_1.2_for_iOS_20180627_60714_es_ES_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24287, 'tasks_AW_VMware_People_Search_1.2_for_iOS_20180627_60715_fr_FR_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24288, 'tasks_AW_VMware_People_Search_1.2_for_iOS_20180627_60716_it_IT_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24289, 'tasks_AW_VMware_People_Search_1.2_for_iOS_20180627_60717_ja_JP_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24290, 'tasks_AW_VMware_People_Search_1.2_for_iOS_20180627_60718_ko_KR_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24291, 'tasks_AW_VMware_People_Search_1.2_for_iOS_20180627_60719_nl_NL_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24292, 'tasks_AW_VMware_People_Search_1.2_for_iOS_20180627_60720_pt_BR_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24293, 'tasks_AW_VMware_People_Search_1.2_for_iOS_20180627_60721_ru_RU_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24294, 'tasks_AW_VMware_People_Search_1.2_for_iOS_20180627_60722_sv_SE_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24295, 'tasks_AW_VMware_People_Search_1.2_for_iOS_20180627_60723_zh_CN_xliff.xlz', '1', 1245, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24616, 'AW_Android Browser 6.15 - WN_20180628_cs_CZ.xlz', '1', 1262, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24617, 'AW_Android Browser 6.15 - WN_20180628_es_ES.xlz', '1', 1262, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24618, 'AW_Android Browser 6.15 - WN_20180628_ja_JP.xlz', '0', 1262, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24619, 'AW_Android Browser 6.15 - WN_20180628_de_DE.xlz', '1', 1262, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24620, 'AW_Android Browser 6.15 - WN_20180628_it_IT.xlz', '1', 1262, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24621, 'AW_Android Browser 6.15 - WN_20180628_da_DK.xlz', '0', 1262, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24622, 'AW_Android Browser 6.15 - WN_20180628_fr_FR.xlz', '1', 1262, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24623, 'AW_Android Browser 6.15 - WN_20180628_pl_PL.xlz', '1', 1262, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24624, 'AW_Android Browser 6.15 - WN_20180628_sv_SE.xlz', '1', 1262, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24625, 'AW_Android Browser 6.15 - WN_20180628_nl_NL.xlz', '1', 1262, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24626, 'AW_Android Browser 6.15 - WN_20180628_ru_RU.xlz', '0', 1262, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24627, 'AW_Android Browser 6.15 - WN_20180628_ko_KR.xlz', '1', 1262, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24628, 'AW_Android Browser 6.15 - WN_20180628_pt_BR.xlz', '1', 1262, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24629, 'AW_Android Browser 6.15 - WN_20180628_zh_CN.xlz', '1', 1262, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24630, 'AW_Android Browser 6.15 - WN_20180628_tr_TR.xlz', '1', 1262, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24631, 'AW_Android Browser 6.15 - WN_20180628_zh_TW.xlz', '1', 1262, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24688, 'AW-Browser 6.15 for iOS_20180629_ja_JP.xlz', '1', 1269, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24689, 'AW-Browser 6.15 for iOS_20180629_de_DE.xlz', '1', 1269, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24690, 'AW-Browser 6.15 for iOS_20180629_pt_BR.xlz', '1', 1269, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24691, 'AW-Browser 6.15 for iOS_20180629_ko_KR.xlz', '1', 1269, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24692, 'AW-Browser 6.15 for iOS_20180629_nl_NL.xlz', '1', 1269, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24693, 'AW-Browser 6.15 for iOS_20180629_fr_FR.xlz', '1', 1269, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24694, 'AW-Browser 6.15 for iOS_20180629_es_ES.xlz', '1', 1269, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24695, 'AW-Browser 6.15 for iOS_20180629_it_IT.xlz', '1', 1269, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24696, 'AW-Browser 6.15 for iOS_20180629_sv_SE.xlz', '1', 1269, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24697, 'AW-Browser 6.15 for iOS_20180629_ru_RU.xlz', '1', 1269, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (24698, 'AW-Browser 6.15 for iOS_20180629_zh_CN.xlz', '1', 1269, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (25016, 'tasks_AW_Boxer_4.14_for_iOS_20180704.docx_61328_de_DE_xliff.xlz', '1', 1304, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (25017, 'tasks_AW_Boxer_4.14_for_iOS_20180704.docx_61329_es_ES_xliff.xlz', '1', 1304, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (25019, 'tasks_AW_Boxer_4.14_for_iOS_20180704.docx_61331_it_IT_xliff.xlz', '1', 1304, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (25020, 'tasks_AW_Boxer_4.14_for_iOS_20180704.docx_61332_ja_JP_xliff.xlz', '1', 1304, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (25022, 'tasks_AW_Boxer_4.14_for_iOS_20180704.docx_61334_nl_NL_xliff.xlz', '1', 1304, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (25023, 'tasks_AW_Boxer_4.14_for_iOS_20180704.docx_61335_pt_BR_xliff.xlz', '1', 1304, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (25024, 'tasks_AW_Boxer_4.14_for_iOS_20180704.docx_61336_ru_RU_xliff.xlz', '1', 1304, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (25025, 'tasks_AW_Boxer_4.14_for_iOS_20180704.docx_61337_sv_SE_xliff.xlz', '1', 1304, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (26127, 'vSphere6.7U1_HostClient_UI_drop1_de_DE.xlz', '1', 1368, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (26129, 'tasks_vSphere6.7U1_HostClient_UI_drop1_61542_zh_TW_desktopWorkbench.xlz', '1', 1368, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (26130, 'tasks_vSphere6.7U1_HostClient_UI_drop1_61541_zh_CN_desktopWorkbench.xlz', '1', 1368, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (26131, 'tasks_vSphere6.7U1_HostClient_UI_drop1_61540_ko_KR_desktopWorkbench.xlz', '1', 1368, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (26132, 'tasks_vSphere6.7U1_HostClient_UI_drop1_61539_ja_JP_desktopWorkbench.xlz', '1', 1368, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (26133, 'tasks_vSphere6.7U1_HostClient_UI_drop1_61538_fr_FR_desktopWorkbench.xlz', '1', 1368, '0', '1');
INSERT INTO `file_status` (`file_info_id`, `file_name`, `is_submited`, `job_id`, `q_complete`, `t_complete`) VALUES (26134, 'tasks_vSphere6.7U1_HostClient_UI_drop1_61537_es_ES_desktopWorkbench.xlz', '1', 1368, '0', '1');
